### ISSUE TITLE
Switch from pygments to rogue for highlighting

### ISSUE THREAD

**Issue by ClaytonJY** [AnnArborRUserGroup/AnnArborRUserGroup.github.io#14]
Right now, a new build of the site emails an annoying error:

> You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors

Should be an easy fix.

**Comment by ellisvalentiner** [comment]
see [line 12](https://github.com/AnnArborRUserGroup/AnnArborRUserGroup.github.io/blob/master/_config.yml#L12) in `_config.yml`
