### ISSUE TITLE
Add sponsors to website

### ISSUE THREAD

**Issue by ClaytonJY** [AnnArborRUserGroup/AnnArborRUserGroup.github.io#16]
We need to display/promote our sponsors in some minimally obtrusive way on the website. As part of this, we should also create and commit to a policy about sponsorship rotation, rules for how long different sponsorships remain in the list.

**Comment by ellisvalentiner** [comment]
Agreed.

Adding something like `sponsors.md` to the top-level directory will generate a sponsors page on the sidebar.

**Comment by ClaytonJY** [comment]
Closed by #20.
