### ISSUE TITLE
"Go to the Meetup Page" links all broken

### ISSUE THREAD

**Issue by ClaytonJY** [AnnArborRUserGroup/AnnArborRUserGroup.github.io#17]
This link shows up at the bottom of each post, but rather than pointing to the appropriate meetup event, they all point right back to the website home page.

**Comment by ellisvalentiner** [comment]
For each Meetup there is a file in `_posts/`. The YAML should have a `meetup` property with the link to the specific Meetup. It is likely that I have been forgetting to include these or haven't been updating it to the correct link for each Meetup.

**Comment by ClaytonJY** [comment]
Newer posts mostly work, but I need to go update some older ones.
