### ISSUE TITLE
Update sponsors

### ISSUE THREAD

**Issue by ellisvalentiner** [AnnArborRUserGroup/AnnArborRUserGroup.github.io#29]
At minimum we need to add R Consortium info:

> (1) Remind your members about the R Consortium and R Community Code of Conduct.
>  
> (2) Display the R Consortium logo on your group website in recognition of the sponsorship. A zip file containing R Consortium logos should be attached to this email.  If your group is using meetup.com, please add the R Consortium logo to the "sponsors" section of your group page.

**Comment by ClaytonJY** [comment]
Fixed by #32.
